// <auto-generated />
using LensBackend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260123221952_MoreLenses")]
    partial class MoreLenses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LensBackend.Models.Lens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aperture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Compatibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FocalLength")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsPopular")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxFocal")
                        .HasColumnType("integer");

                    b.Property<int>("MinFocal")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aperture = "f/1.8",
                            Brand = "Canon",
                            Compatibility = "Canon EF",
                            Description = "Классический портретный объектив.",
                            FocalLength = "85mm",
                            IsPopular = true,
                            MaxFocal = 85,
                            MinFocal = 85,
                            Name = "Canon EF 85mm f/1.8",
                            Price = 35000m,
                            Type = "portrait"
                        },
                        new
                        {
                            Id = 2,
                            Aperture = "f/2.8",
                            Brand = "Canon",
                            Compatibility = "Canon EF",
                            Description = "Универсальный зум для пейзажей и репортажей.",
                            FocalLength = "24–70mm",
                            IsPopular = true,
                            MaxFocal = 70,
                            MinFocal = 24,
                            Name = "Canon EF 24-70mm f/2.8",
                            Price = 90000m,
                            Type = "landscape"
                        },
                        new
                        {
                            Id = 3,
                            Aperture = "f/2.8",
                            Brand = "Nikon",
                            Compatibility = "Nikon F",
                            Description = "Телезум для спорта и съёмки с расстояния.",
                            FocalLength = "70–200mm",
                            IsPopular = true,
                            MaxFocal = 200,
                            MinFocal = 70,
                            Name = "Nikon AF-S 70-200mm f/2.8",
                            Price = 130000m,
                            Type = "sport"
                        },
                        new
                        {
                            Id = 4,
                            Aperture = "f/2.8",
                            Brand = "Sony",
                            Compatibility = "Sony FE",
                            Description = "Макрообъектив для съёмки мелких деталей.",
                            FocalLength = "90mm",
                            MaxFocal = 90,
                            MinFocal = 90,
                            Name = "Sony FE 90mm f/2.8 Macro",
                            Price = 110000m,
                            Type = "macro"
                        },
                        new
                        {
                            Id = 5,
                            Aperture = "f/1.4",
                            Brand = "Sigma",
                            Compatibility = "Sony E / m4/3",
                            Description = "Широкоугольный объектив для пейзажей и интерьеров.",
                            FocalLength = "16mm",
                            MaxFocal = 16,
                            MinFocal = 16,
                            Name = "Sigma 16mm f/1.4 DC DN",
                            Price = 45000m,
                            Type = "landscape"
                        },
                        new
                        {
                            Id = 6,
                            Aperture = "f/1.4",
                            Brand = "Canon",
                            Compatibility = "Canon EF",
                            Description = "Стандартный объектив с большой диафрагмой для портретов.",
                            FocalLength = "50mm",
                            MaxFocal = 50,
                            MinFocal = 50,
                            Name = "Canon EF 50mm f/1.4",
                            Price = 25000m,
                            Type = "portrait"
                        },
                        new
                        {
                            Id = 7,
                            Aperture = "f/1.8",
                            Brand = "Nikon",
                            Compatibility = "Nikon F",
                            Description = "Доступный портретный объектив с отличной оптикой.",
                            FocalLength = "50mm",
                            MaxFocal = 50,
                            MinFocal = 50,
                            Name = "Nikon AF-S 50mm f/1.8G",
                            Price = 15000m,
                            Type = "portrait"
                        },
                        new
                        {
                            Id = 8,
                            Aperture = "f/1.8",
                            Brand = "Sony",
                            Compatibility = "Sony FE",
                            Description = "Широкоугольный портретный объектив для полнокадровых камер.",
                            FocalLength = "35mm",
                            MaxFocal = 35,
                            MinFocal = 35,
                            Name = "Sony FE 35mm f/1.8",
                            Price = 40000m,
                            Type = "portrait"
                        },
                        new
                        {
                            Id = 9,
                            Aperture = "f/2.8",
                            Brand = "Tamron",
                            Compatibility = "Sony FE",
                            Description = "Легкий телезум для спорта и портретов.",
                            FocalLength = "70-180mm",
                            MaxFocal = 180,
                            MinFocal = 70,
                            Name = "Tamron 70-180mm f/2.8",
                            Price = 95000m,
                            Type = "sport"
                        },
                        new
                        {
                            Id = 10,
                            Aperture = "f/2.8",
                            Brand = "Sigma",
                            Compatibility = "Sony FE / Leica L",
                            Description = "Высококачественный зум для пейзажной съемки.",
                            FocalLength = "24-70mm",
                            MaxFocal = 70,
                            MinFocal = 24,
                            Name = "Sigma 24-70mm f/2.8 DG DN",
                            Price = 85000m,
                            Type = "landscape"
                        },
                        new
                        {
                            Id = 11,
                            Aperture = "f/3.5-5.6",
                            Brand = "Canon",
                            Compatibility = "Canon EF-S",
                            Description = "Бюджетный кит-объектив для начинающих.",
                            FocalLength = "18-55mm",
                            MaxFocal = 55,
                            MinFocal = 18,
                            Name = "Canon EF-S 18-55mm f/3.5-5.6",
                            Price = 12000m,
                            Type = "landscape"
                        },
                        new
                        {
                            Id = 12,
                            Aperture = "f/3.5-5.6",
                            Brand = "Nikon",
                            Compatibility = "Nikon F",
                            Description = "Компактный зум для повседневной съемки.",
                            FocalLength = "18-55mm",
                            MaxFocal = 55,
                            MinFocal = 18,
                            Name = "Nikon AF-P 18-55mm f/3.5-5.6G",
                            Price = 10000m,
                            Type = "landscape"
                        },
                        new
                        {
                            Id = 13,
                            Aperture = "f/2.8",
                            Brand = "Sony",
                            Compatibility = "Sony E",
                            Description = "Профессиональный зум с постоянной диафрагмой.",
                            FocalLength = "16-55mm",
                            MaxFocal = 55,
                            MinFocal = 16,
                            Name = "Sony E 16-55mm f/2.8 G",
                            Price = 120000m,
                            Type = "landscape"
                        },
                        new
                        {
                            Id = 14,
                            Aperture = "f/5-6.3",
                            Brand = "Sigma",
                            Compatibility = "Sony FE / Leica L",
                            Description = "Длиннофокусный зум для дикой природы.",
                            FocalLength = "100-400mm",
                            MaxFocal = 400,
                            MinFocal = 100,
                            Name = "Sigma 100-400mm f/5-6.3 DG DN OS",
                            Price = 70000m,
                            Type = "sport"
                        },
                        new
                        {
                            Id = 15,
                            Aperture = "f/2.8-4",
                            Brand = "Tamron",
                            Compatibility = "Canon EF / Nikon F",
                            Description = "Универсальный зум с хорошей оптикой.",
                            FocalLength = "17-70mm",
                            MaxFocal = 70,
                            MinFocal = 17,
                            Name = "Tamron 17-70mm f/2.8-4",
                            Price = 50000m,
                            Type = "landscape"
                        },
                        new
                        {
                            Id = 16,
                            Aperture = "f/4.5-5.6",
                            Brand = "Canon",
                            Compatibility = "Canon EF",
                            Description = "L-серия для профессиональной спортивной съемки.",
                            FocalLength = "100-400mm",
                            MaxFocal = 400,
                            MinFocal = 100,
                            Name = "Canon EF 100-400mm f/4.5-5.6L IS II",
                            Price = 180000m,
                            Type = "sport"
                        },
                        new
                        {
                            Id = 17,
                            Aperture = "f/4.5-5.6",
                            Brand = "Nikon",
                            Compatibility = "Nikon F",
                            Description = "Мощный зум с оптической стабилизацией.",
                            FocalLength = "80-400mm",
                            MaxFocal = 400,
                            MinFocal = 80,
                            Name = "Nikon AF-S 80-400mm f/4.5-5.6G ED VR",
                            Price = 160000m,
                            Type = "sport"
                        },
                        new
                        {
                            Id = 18,
                            Aperture = "f/4.5-5.6",
                            Brand = "Sony",
                            Compatibility = "Sony FE",
                            Description = "G Master зум для профессионалов.",
                            FocalLength = "100-400mm",
                            MaxFocal = 400,
                            MinFocal = 100,
                            Name = "Sony FE 100-400mm f/4.5-5.6 GM OSS",
                            Price = 220000m,
                            Type = "sport"
                        },
                        new
                        {
                            Id = 19,
                            Aperture = "f/5-6.3",
                            Brand = "Sigma",
                            Compatibility = "Canon EF / Nikon F / Sony FE",
                            Description = "Супер-телезум для птиц и спорта.",
                            FocalLength = "150-600mm",
                            MaxFocal = 600,
                            MinFocal = 150,
                            Name = "Sigma 150-600mm f/5-6.3 DG OS HSM",
                            Price = 90000m,
                            Type = "sport"
                        },
                        new
                        {
                            Id = 20,
                            Aperture = "f/5-6.3",
                            Brand = "Tamron",
                            Compatibility = "Canon EF / Nikon F",
                            Description = "Вторая версия с улучшенной оптикой.",
                            FocalLength = "150-600mm",
                            MaxFocal = 600,
                            MinFocal = 150,
                            Name = "Tamron 150-600mm f/5-6.3 Di VC USD G2",
                            Price = 100000m,
                            Type = "sport"
                        },
                        new
                        {
                            Id = 21,
                            Aperture = "f/4",
                            Brand = "Canon",
                            Compatibility = "Canon EF",
                            Description = "Фишай объектив для креативной съемки.",
                            FocalLength = "8-15mm",
                            MaxFocal = 15,
                            MinFocal = 8,
                            Name = "Canon EF 8-15mm f/4L Fisheye USM",
                            Price = 120000m,
                            Type = "landscape"
                        },
                        new
                        {
                            Id = 22,
                            Aperture = "f/4",
                            Brand = "Nikon",
                            Compatibility = "Nikon F",
                            Description = "Широкоугольный зум с стабилизацией.",
                            FocalLength = "16-35mm",
                            MaxFocal = 35,
                            MinFocal = 16,
                            Name = "Nikon AF-S 16-35mm f/4G ED VR",
                            Price = 110000m,
                            Type = "landscape"
                        },
                        new
                        {
                            Id = 23,
                            Aperture = "f/4",
                            Brand = "Sony",
                            Compatibility = "Sony FE",
                            Description = "Сверхширокоугольный зум для архитектуры.",
                            FocalLength = "12-24mm",
                            MaxFocal = 24,
                            MinFocal = 12,
                            Name = "Sony FE 12-24mm f/4 G",
                            Price = 160000m,
                            Type = "landscape"
                        },
                        new
                        {
                            Id = 24,
                            Aperture = "f/2.8",
                            Brand = "Sigma",
                            Compatibility = "Canon EF / Nikon F / Sony FE",
                            Description = "Высококачественный широкоугольник.",
                            FocalLength = "14-24mm",
                            MaxFocal = 24,
                            MinFocal = 14,
                            Name = "Sigma 14-24mm f/2.8 DG HSM",
                            Price = 130000m,
                            Type = "landscape"
                        },
                        new
                        {
                            Id = 25,
                            Aperture = "f/3.5-4.5",
                            Brand = "Tamron",
                            Compatibility = "Canon EF / Nikon F",
                            Description = "Доступный сверхширокоугольный зум.",
                            FocalLength = "10-24mm",
                            MaxFocal = 24,
                            MinFocal = 10,
                            Name = "Tamron 10-24mm f/3.5-4.5",
                            Price = 40000m,
                            Type = "landscape"
                        },
                        new
                        {
                            Id = 26,
                            Aperture = "f/2.8",
                            Brand = "Canon",
                            Compatibility = "Canon EF",
                            Description = "Макро-объектив с оптической стабилизацией.",
                            FocalLength = "100mm",
                            MaxFocal = 100,
                            MinFocal = 100,
                            Name = "Canon EF 100mm f/2.8L Macro IS USM",
                            Price = 80000m,
                            Type = "macro"
                        },
                        new
                        {
                            Id = 27,
                            Aperture = "f/2.8",
                            Brand = "Nikon",
                            Compatibility = "Nikon F",
                            Description = "Классический макро-объектив Nikon.",
                            FocalLength = "105mm",
                            MaxFocal = 105,
                            MinFocal = 105,
                            Name = "Nikon AF-S 105mm f/2.8G ED-IF VR",
                            Price = 90000m,
                            Type = "macro"
                        },
                        new
                        {
                            Id = 28,
                            Aperture = "f/2.8",
                            Brand = "Sony",
                            Compatibility = "Sony FE",
                            Description = "G-объектив для макросъемки.",
                            FocalLength = "90mm",
                            MaxFocal = 90,
                            MinFocal = 90,
                            Name = "Sony FE 90mm f/2.8 Macro G OSS",
                            Price = 100000m,
                            Type = "macro"
                        },
                        new
                        {
                            Id = 29,
                            Aperture = "f/2.8",
                            Brand = "Sigma",
                            Compatibility = "Canon EF / Nikon F / Sony FE",
                            Description = "Доступный макро-объектив с хорошей оптикой.",
                            FocalLength = "70mm",
                            MaxFocal = 70,
                            MinFocal = 70,
                            Name = "Sigma 70mm f/2.8 DG Macro",
                            Price = 50000m,
                            Type = "macro"
                        },
                        new
                        {
                            Id = 30,
                            Aperture = "f/2.8",
                            Brand = "Tamron",
                            Compatibility = "Canon EF / Nikon F",
                            Description = "Макро с вибро-подавлением.",
                            FocalLength = "90mm",
                            MaxFocal = 90,
                            MinFocal = 90,
                            Name = "Tamron 90mm f/2.8 Di VC USD Macro",
                            Price = 55000m,
                            Type = "macro"
                        },
                        new
                        {
                            Id = 31,
                            Aperture = "f/2.8",
                            Brand = "Canon",
                            Compatibility = "Canon EF",
                            Description = "Супер-телефото для профессионалов.",
                            FocalLength = "400mm",
                            MaxFocal = 400,
                            MinFocal = 400,
                            Name = "Canon EF 400mm f/2.8L IS III USM",
                            Price = 1200000m,
                            Type = "sport"
                        },
                        new
                        {
                            Id = 32,
                            Aperture = "f/2.8",
                            Brand = "Nikon",
                            Compatibility = "Nikon F",
                            Description = "Флагманский телеобъектив Nikon.",
                            FocalLength = "400mm",
                            MaxFocal = 400,
                            MinFocal = 400,
                            Name = "Nikon AF-S 400mm f/2.8E FL ED VR",
                            Price = 1300000m,
                            Type = "sport"
                        },
                        new
                        {
                            Id = 33,
                            Aperture = "f/2.8",
                            Brand = "Sony",
                            Compatibility = "Sony FE",
                            Description = "G Master 400мм для спорта и дикой природы.",
                            FocalLength = "400mm",
                            MaxFocal = 400,
                            MinFocal = 400,
                            Name = "Sony FE 400mm f/2.8 GM OSS",
                            Price = 1400000m,
                            Type = "sport"
                        },
                        new
                        {
                            Id = 34,
                            Aperture = "f/1.4",
                            Brand = "Sigma",
                            Compatibility = "Canon EF / Nikon F / Sony FE",
                            Description = "Арт-объектив с большой диафрагмой.",
                            FocalLength = "50mm",
                            MaxFocal = 50,
                            MinFocal = 50,
                            Name = "Sigma 50mm f/1.4 DG HSM",
                            Price = 60000m,
                            Type = "portrait"
                        },
                        new
                        {
                            Id = 35,
                            Aperture = "f/1.8",
                            Brand = "Tamron",
                            Compatibility = "Canon EF / Nikon F",
                            Description = "Широкоугольный объектив с стабилизацией.",
                            FocalLength = "35mm",
                            MaxFocal = 35,
                            MinFocal = 35,
                            Name = "Tamron 35mm f/1.8 VC",
                            Price = 30000m,
                            Type = "portrait"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
