// <auto-generated />
using LensBackend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260123221711_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LensBackend.Models.Lens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aperture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Compatibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FocalLength")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsPopular")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxFocal")
                        .HasColumnType("integer");

                    b.Property<int>("MinFocal")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aperture = "f/1.8",
                            Brand = "Canon",
                            Compatibility = "Canon EF",
                            Description = "Классический портретный объектив.",
                            FocalLength = "85mm",
                            IsPopular = true,
                            MaxFocal = 85,
                            MinFocal = 85,
                            Name = "Canon EF 85mm f/1.8",
                            Price = 35000m,
                            Type = "portrait"
                        },
                        new
                        {
                            Id = 2,
                            Aperture = "f/2.8",
                            Brand = "Canon",
                            Compatibility = "Canon EF",
                            Description = "Универсальный зум для пейзажей и репортажей.",
                            FocalLength = "24–70mm",
                            IsPopular = true,
                            MaxFocal = 70,
                            MinFocal = 24,
                            Name = "Canon EF 24-70mm f/2.8",
                            Price = 90000m,
                            Type = "landscape"
                        },
                        new
                        {
                            Id = 3,
                            Aperture = "f/2.8",
                            Brand = "Nikon",
                            Compatibility = "Nikon F",
                            Description = "Телезум для спорта и съёмки с расстояния.",
                            FocalLength = "70–200mm",
                            IsPopular = true,
                            MaxFocal = 200,
                            MinFocal = 70,
                            Name = "Nikon AF-S 70-200mm f/2.8",
                            Price = 130000m,
                            Type = "sport"
                        },
                        new
                        {
                            Id = 4,
                            Aperture = "f/2.8",
                            Brand = "Sony",
                            Compatibility = "Sony FE",
                            Description = "Макрообъектив для съёмки мелких деталей.",
                            FocalLength = "90mm",
                            MaxFocal = 90,
                            MinFocal = 90,
                            Name = "Sony FE 90mm f/2.8 Macro",
                            Price = 110000m,
                            Type = "macro"
                        },
                        new
                        {
                            Id = 5,
                            Aperture = "f/1.4",
                            Brand = "Sigma",
                            Compatibility = "Sony E / m4/3",
                            Description = "Широкоугольный объектив для пейзажей и интерьеров.",
                            FocalLength = "16mm",
                            MaxFocal = 16,
                            MinFocal = 16,
                            Name = "Sigma 16mm f/1.4 DC DN",
                            Price = 45000m,
                            Type = "landscape"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
